In [49]:
import numpy as np
import pandas as pd


In [50]:
np.__version__

'1.19.5'

In [51]:
print (np.__version__) #question 1

1.19.5


In [52]:
print(pd.__version__) #question 2

1.3.1


In [53]:
df = pd.read_csv("hw.csv")
df.head()  #Getting the data

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [54]:
 df[df['Make'] == 'BMW'].MSRP.mean()      # question 3

61546.76347305389

In [55]:
df [df['Year'] >= 2015].isnull().sum()  #df.isnull().sum()   51  question 4

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [56]:
#question 5 a)
print(round(df['Engine HP'].mean()))                           

249


In [57]:
#question 5 b)
df['Engine HP'] = df['Engine HP'].fillna(df['Engine HP'].mean())


In [58]:
#question 5 c)
df['Engine HP'].mean()

249.38607007176023

In [59]:
 print(round(df['Engine HP'].mean()))                           

249


In [60]:
rr = pd.DataFrame()
rr =  df[df['Make'] == 'Rolls-Royce'][['Engine HP','Engine Cylinders', 'highway MPG']].drop_duplicates()     #question 6 a,b,c
rr

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [61]:
X = np.array(rr)  #question 6 d
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [62]:

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [63]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
     
    return result

In [64]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [65]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [78]:
XTtranspose  = X.T #6E
XTX = matrix_matrix_multiplication(X, X.T)
XTX
# stop hereXT

array([[105914., 183356., 183386., 183371., 104971., 147606., 203211.],
       [183356., 317474., 317512., 317493., 181715., 255544., 351855.],
       [183386., 317512., 317554., 317533., 181745., 255582., 351897.],
       [183371., 317493., 317533., 317513., 181730., 255563., 351876.],
       [104971., 181715., 181745., 181730., 104053., 146295., 201387.],
       [147606., 255544., 255582., 255563., 146295., 205714., 283215.],
       [203211., 351855., 351897., 351876., 201387., 283215., 389961.]])

In [87]:
XTtranspose

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [68]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [81]:
VS = XTX[[0,1,2,3,4,5,6]]
VS
#invd = np.linalg.inv(X)
#invd
#print(np.eye(3))
#VS =X[[0,1,2]]
VS

array([[105914., 183356., 183386., 183371., 104971., 147606., 203211.],
       [183356., 317474., 317512., 317493., 181715., 255544., 351855.],
       [183386., 317512., 317554., 317533., 181745., 255582., 351897.],
       [183371., 317493., 317533., 317513., 181730., 255563., 351876.],
       [104971., 181715., 181745., 181730., 104053., 146295., 201387.],
       [147606., 255544., 255582., 255563., 146295., 205714., 283215.],
       [203211., 351855., 351897., 351876., 201387., 283215., 389961.]])

In [80]:
I = np.eye(7)
I

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [83]:
XTXI = np.linalg.inv(XTX)
XTXI
#print(np.eye(3))
#VS =X[[0,1,2]]
VS

array([[105914., 183356., 183386., 183371., 104971., 147606., 203211.],
       [183356., 317474., 317512., 317493., 181715., 255544., 351855.],
       [183386., 317512., 317554., 317533., 181745., 255582., 351897.],
       [183371., 317493., 317533., 317513., 181730., 255563., 351876.],
       [104971., 181715., 181745., 181730., 104053., 146295., 201387.],
       [147606., 255544., 255582., 255563., 146295., 205714., 283215.],
       [203211., 351855., 351897., 351876., 201387., 283215., 389961.]])

In [84]:
XTX

array([[105914., 183356., 183386., 183371., 104971., 147606., 203211.],
       [183356., 317474., 317512., 317493., 181715., 255544., 351855.],
       [183386., 317512., 317554., 317533., 181745., 255582., 351897.],
       [183371., 317493., 317533., 317513., 181730., 255563., 351876.],
       [104971., 181715., 181745., 181730., 104053., 146295., 201387.],
       [147606., 255544., 255582., 255563., 146295., 205714., 283215.],
       [203211., 351855., 351897., 351876., 201387., 283215., 389961.]])

In [85]:
XTX.dot(XTXI)

array([[ 0.57426071,  1.22481155, -1.07983017, -0.44962311,  0.11635017,
         0.        ,  0.07287598],
       [-0.74640274,  0.65777969, -1.19269943,  0.68444061,  0.47171974,
         0.        , -0.15026855],
       [ 0.48373795,  0.65761948, -0.67049026, -1.31523895,  0.05798912,
         0.        ,  4.33679199],
       [ 0.6186676 ,  0.65769958,  0.06840515, -1.31539917, -1.23514557,
         0.        , -3.40673828],
       [-0.2061348 ,  0.23176956, -0.90148544, -0.46353912,  0.76265144,
         0.        ,  1.42053223],
       [-0.21918106, -1.08037949, -0.06025314, -0.83924103, -0.08852196,
         0.        ,  0.8536377 ],
       [-1.58590317,  0.51241684, -1.97121048, -1.02483368,  0.81412315,
         0.        ,  1.75280762]])

In [96]:
sum = np.sum(XTXI)
sum

-1570497826.622116

In [86]:
#question 7 
y =np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [90]:
newval = matrix_matrix_multiplication(XTtranspose,XTXI) # multiply inverseXTX by Xt
newval

array([[-0.00976562,  0.0078125 ,  0.00390625,  0.        , -0.00585938,
         0.        , -0.00976562],
       [-0.23814392,  0.0791626 , -0.04260254,  0.0345459 ,  0.20599365,
         0.04174805, -0.07678223],
       [ 0.41012573, -0.19488525, -0.12512207, -0.09637451,  0.01449585,
        -0.09545898,  0.22399902]])

In [91]:
W = newval.dot(y)

In [92]:
W


array([-16.2109375 ,  -6.28967285, 192.04711914])

In [95]:
W


array([-16.2109375 ,  -6.28967285, 192.04711914])